title: "Mehdi Karbalay-Ghareh"
email: "m.karbalay.gh@gmail.com"
description: "Academic personal website"
url: "https://mkarbalaygh.github.io"
baseurl: ""
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/
