title: "Mehdi Karbalayghareh"
email: "m.karbalay.gh@gmail.com"
description: "Academic personal website"
url: "https://mkarbalaygh.github.io"
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

collections:
  pages:
    output: true
    permalink: /:path/
